// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGWyFAR7RZprmI_Qv6C3yp5wiG7tdx7So',
    appId: '1:535981417411:web:e16925af25ce1c2fcf1376',
    messagingSenderId: '535981417411',
    projectId: 'due-pam-app',
    authDomain: 'due-pam-app.firebaseapp.com',
    storageBucket: 'due-pam-app.firebasestorage.app',
    measurementId: 'G-MC7YG9MS53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCMvAn5UT2XZmO32jVhnlQpPSRFNkTL4o',
    appId: '1:535981417411:android:9b0092d611e082cfcf1376',
    messagingSenderId: '535981417411',
    projectId: 'due-pam-app',
    storageBucket: 'due-pam-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4nX1EuskyxNAehRXnz6fBndEHB47YNFI',
    appId: '1:535981417411:ios:08e0d914452bffefcf1376',
    messagingSenderId: '535981417411',
    projectId: 'due-pam-app',
    storageBucket: 'due-pam-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicatin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4nX1EuskyxNAehRXnz6fBndEHB47YNFI',
    appId: '1:535981417411:ios:08e0d914452bffefcf1376',
    messagingSenderId: '535981417411',
    projectId: 'due-pam-app',
    storageBucket: 'due-pam-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicatin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGWyFAR7RZprmI_Qv6C3yp5wiG7tdx7So',
    appId: '1:535981417411:web:55f0f98540293683cf1376',
    messagingSenderId: '535981417411',
    projectId: 'due-pam-app',
    authDomain: 'due-pam-app.firebaseapp.com',
    storageBucket: 'due-pam-app.firebasestorage.app',
    measurementId: 'G-E6J925B8YC',
  );

}